### ISSUE TITLE
verify artifact is pushed to Maven central and setup the ci

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-registry-common#1]

**Comment by jordanpadams** [comment]
@tloubrieu-jpl i modified the title slightly to be what i think you mean? we want to push this library to maven central so it can be used by other apps. that being said, this should be as simple as adding the `unstable_ci.yml` from another repo. the roundup-action does all the magic from there 🎉

**Comment by tloubrieu-jpl** [comment]
@jordanpadams thanks Jordan, this is not much indeed, I initially created the ticket so I don't forget to come back to that.

**Comment by tloubrieu-jpl** [comment]
The artifact is pushed properly on the maven repo https://oss.sonatype.org/content/repositories/snapshots/gov/nasa/pds/registry-common/1.0.0-SNAPSHOT/
